site_name: Loop documentation

markdown_extensions:
    - meta
    - admonition
    - toc:
        permalink: true
    
plugins:
  - search

theme:
  name: material
  custom_dir: ../overrides
  language: ro
  features:
      - navigation.tabs

nav:
- 'None' : 'index.md' 
- 'None' :
    - 'None' : 'faqs/docs-faqs.md'
    - 'None' : 'faqs/FAQs.md'
    - 'None' : 'faqs/omnipod-faqs.md'
    - 'None' : 'faqs/branch-faqs.md'
    - 'None' : 'faqs/update-faqs.md'
    - 'None' : 'faqs/ios13.md'
    - 'None' : 'faqs/rileylink-faqs.md'
    - 'None' : 'faqs/algorithm-faqs.md'
    - 'None' : 'faqs/cgm-faqs.md'
    - 'None' : 'faqs/safety-faqs.md'
- 'None' :
    - 'None' : 'build/overview.md' 
    - 'None' : 'build/step1.md'
    - 'None' : 'build/step2.md'
    - 'None' : 'build/step3.md'
    - 'None' : 'build/step4.md'
    - 'None' : 'build/step5.md'
    - 'None' : 'build/step6.md'
    - 'None' : 'build/step7.md'
    - 'None' : 'build/step8.md'
    - 'None' : 'build/step9.md'
    - 'None' : 'build/step10.md'
    - 'None' : 'build/step11.md'
    - 'None' : 'build/step12.md'
    - 'None' : 'build/step13.md'
    - 'None' : 'build/step14.md'
    - 'None' : 'build/build_errors.md'
    - 'None' : 'build/code_customization.md'
    - 'None' : 'build/updating.md'
    - 'None' : 'build/loopworkspace.md'
- 'None' :
    - 'None' : 'operation/overview.md'
    - 'Step 1 : Health Permissions' : 'build/health.md'
    - 'Step 2 : Add Pump' :
        - 'None' : 'operation/loop-settings/mdt-pump.md'
        - 'None' : 'operation/loop-settings/omnipod-pump.md'
    - 'Step 3 : Add CGM' : 'operation/loop-settings/cgm.md'
    - 'Step 4 :Configurations' : 'operation/loop-settings/configurations.md'
    - 'Step 5 : Loop Services' : 'operation/loop-settings/services.md'
    - 'None' : 'operation/loop-settings/displays.md'
    - 'None' : 'operation/loop-settings/rileylink.md'
- 'None' :
    - 'None' :
        - 'None' : 'operation/features/carbs.md'
        - 'None' : 'operation/features/bolus.md'
        - 'None' : 'operation/features/workout.md'
        - 'None' : 'operation/features/premeal.md'
        - 'None' : 'operation/features/healthapp.md'
        - 'None' : 'operation/features/ice.md'
        - 'None' : 'operation/features/watch.md'
        - 'None' : 'operation/features/widget.md'
        - 'None' : 'operation/features/notifications.md'
        - 'None' : 'operation/features/battery.md'
    - 'None' :
        - 'None' : 'operation/loop/open-loop.md'
        - 'None' : 'operation/loop/close-loop.md'
        - 'None' : 'operation/loop/looptips.md'
    - 'None' :
        - 'None' : 'operation/algorithm/overview.md'
        - 'None' : 'operation/algorithm/bolus.md'
        - 'None' : 'operation/algorithm/prediction.md'
        - 'None' : 'operation/algorithm/temp-basal.md'
    - 'None' :
        - 'None' : 'troubleshooting/overview.md'
        - 'None' : 'troubleshooting/loop-crashing.md'
        - 'None' : 'troubleshooting/yellow-red-loop.md'
        - 'None' : 'troubleshooting/pod-pairing.md'
        - 'None' : 'troubleshooting/uncertain-bolus.md'
        - 'None' : 'troubleshooting/priming.md'
        - 'None' : 'troubleshooting/time-change.md'
        - 'None' : 'troubleshooting/pump-errors.md'
        - 'None' : 'troubleshooting/omnipod-faults.md'
- 'None' :
    - 'None' : 'nightscout/overview.md'
    - 'None' : 'nightscout/new_user.md'
    - 'None' : 'nightscout/update_user.md'
    - 'None' : 'nightscout/troublehoot.md'
    - 'None' : 'nightscout/remote-overrides.md'
    - 'None' : 'nightscout/ifttt.md'
    - 'None' : 'nightscout/pebble.md'
    - 'None' : 'nightscout/pushover.md'
    - 'None' : 'nightscout/reports.md'
- 'None' :
    - 'None' : 'payitforward/translateloopdocs.md'
