markdown_extensions:
- meta
- admonition
- toc:
    permalink: true
nav:
- Hjem: index.md
- FAQs:
  - Using This Site FAQs: faqs/docs-faqs.md
  - General Loop FAQs: faqs/FAQs.md
  - Omnipod FAQs: faqs/omnipod-faqs.md
  - Branch FAQs: faqs/branch-faqs.md
  - Update/Rebuild Loop FAQs: faqs/update-faqs.md
  - iOS 13 FAQs: faqs/ios13.md
  - RileyLink FAQs: faqs/rileylink-faqs.md
  - Algorithm FAQs: faqs/algorithm-faqs.md
  - CGM FAQs: faqs/cgm-faqs.md
  - Safety Tips: faqs/safety-faqs.md
- Byg app:
  - ' Overblik': build/overview.md
  - Step 1 Compatible Computer: build/step1.md
  - Step 2 Compatible iPhone/iPod touch: build/step2.md
  - Step 3 Compatible Pump: build/step3.md
  - Step 4 Compatible CGM: build/step4.md
  - Step 5 Order a RileyLink: build/step5.md
  - Step 6 Enroll in Apple Developer Program: build/step6.md
  - Step 7 Install Homebrew: build/step7.md
  - Step 8 Download Xcode: build/step8.md
  - Step 9 Xcode Preferences: build/step9.md
  - Step 10 Test Settings: build/step10.md
  - Step 11 Make plans for Loop Data: build/step11.md
  - Step 12 Meet Community: build/step12.md
  - Step 13 Download Loop code: build/step13.md
  - Step 14 Build Loop app: build/step14.md
  - Oh dear! Build errors?: build/build_errors.md
  - Customize your Loop: build/code_customization.md
  - Updating/Rebuilding your Loop: build/updating.md
  - LoopWorkspace: build/loopworkspace.md
- "Ops\xE6tning af app":
  - ' Overblik': operation/overview.md
  - Step 1 - Health Permissions: build/health.md
  - Step 2 - Add Pump:
    - Add Medtronic: operation/loop-settings/mdt-pump.md
    - Add Omnipod: operation/loop-settings/omnipod-pump.md
  - Step 3 - Add CGM: operation/loop-settings/cgm.md
  - Step 4 - Configurations: operation/loop-settings/configurations.md
  - Step 5 - Loop Services: operation/loop-settings/services.md
  - Loop Displays: operation/loop-settings/displays.md
  - RileyLink menu: operation/loop-settings/rileylink.md
- Brugervejledning:
  - "S\xE5dan bruges Loop App":
    - Carb Entries: operation/features/carbs.md
    - Bolus: operation/features/bolus.md
    - Overrides: operation/features/workout.md
    - Pre-meal target: operation/features/premeal.md
    - Health app: operation/features/healthapp.md
    - Using ICE info: operation/features/ice.md
    - Apple Watch: operation/features/watch.md
    - iPhone widget: operation/features/widget.md
    - Loop Notifications: operation/features/notifications.md
    - Pump Battery: operation/features/battery.md
  - Looping Tipps:
    - Open Loop: operation/loop/open-loop.md
    - Closed Loop: operation/loop/close-loop.md
    - Loop Tips: operation/loop/looptips.md
  - Algoritme:
    - ' Overblik': operation/algorithm/overview.md
    - Bolus Recommendations: operation/algorithm/bolus.md
    - Glucose Prediction: operation/algorithm/prediction.md
    - Temp Basal Adjustments: operation/algorithm/temp-basal.md
  - Fejlfinding:
    - ' Overblik': troubleshooting/overview.md
    - Loop App crashes: troubleshooting/loop-crashing.md
    - Red Loop: troubleshooting/yellow-red-loop.md
    - Pod Pairing Failures: troubleshooting/pod-pairing.md
    - Pod Uncertain Boluses: troubleshooting/uncertain-bolus.md
    - MDT Priming and Sites: troubleshooting/priming.md
    - Time Changes: troubleshooting/time-change.md
    - MDT Pump Errors: troubleshooting/pump-errors.md
    - Omnipod Faults: troubleshooting/omnipod-faults.md
- Nightscout:
  - ' Overblik': nightscout/overview.md
  - Brand New NS: nightscout/new_user.md
  - Retrofit Existing NS: nightscout/update_user.md
  - Setup Troubleshooting: nightscout/troublehoot.md
  - Remote Overrides: nightscout/remote-overrides.md
  - IFTTT: nightscout/ifttt.md
  - Pebble: nightscout/pebble.md
  - Remote Notifications: nightscout/pushover.md
  - Reports: nightscout/reports.md
- Pay It Forward:
  - "Overs\xE6t Loopdocs": payitforward/translateloopdocs.md
plugins:
- search
site_name: Loop documentation
theme:
  custom_dir: ../overrides
  features:
  - navigation.tabs
  language: de
  name: material
