# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on: workflow_dispatch
  # Triggers the workflow on push events but only for the main branch
  #push:
    #branches: [ master-translation ]

jobs:
  deploy:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs-material
      - run: pip install mkdocs-bootswatch
      - run: .\scripts\buildsite.ps1
              
      - uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          BRANCH: gh-pages-translation
          FOLDER: site