# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on: workflow_dispatch
  # Triggers the workflow on push events but only for the main branch
  #push:
  #  branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Copycat Action
        # You may pin to the exact commit or the version.
        # uses: andstor/copycat-action@10a8fce94cc066110cb394d6f06814b7f5f06a34
        uses: andstor/copycat-action@v3.2.3
        with:
          src_path: docs
          # The destination path to copy the file(s) or folder(s) to
          dst_path: docs_da_test
          # The name of the owner of the repository to push to
          dst_owner: loopdocs
          # The name of the repository to push to
          dst_repo_name: loopdocs.da
          # The branch name of the source repository
          src_branch: master-da
          # The branch name of the destination repository
          dst_branch: master-da
          # A glob pattern for filtering file paths to be included for copying
          file_filter: *.png
          # A glob pattern for excluding paths
          exclude: *.md, *.yml
